services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/services/catalog/Catalog.API/Dockerfile
    ports:
     - "8080:8080"
    container_name: catalogapi
    depends_on:
     - catalogdb
     - elasticsearch
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - MongoSettings__Connection=mongodb://catalogdb:27017
     - MongoSettings__DatabaseName=CatalogDb
     - LoggingOptions__ApplicationName=Catalog.API
     - LoggingOptions__LogLevel=Information
     - LoggingOptions__ElasticUrl=http://elasticsearch:9200

  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - catalogdbdata:/data/db
 
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/services/basket/Basket.API/Dockerfile

    ports:
     - "8081:8080"
    container_name: basketapi
    depends_on:
     - basketdb
     - rabbitmq
     - elasticsearch
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - CacheSettings__Connection=basketdb:6379
     - GrpcSettings__DiscountUrl=http://discount.api:8082
     - RabbitMQSetting__HostAddress=amqp://guest:guest@rabbitmq:5672
     - LoggingOptions__ApplicationName=Basket.API
     - LoggingOptions__LogLevel=Information
     - LoggingOptions__ElasticUrl=http://elasticsearch:9200

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data

  discountdb:
    image: postgres:18
    container_name: discountdb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: discountdb
    restart: always 
    ports:
      - "5432:5432"
    volumes:
      - discountdbdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d discountdb"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      discountdb:
        condition: service_healthy
    restart: always
    volumes:
      - pgadmindata:/var/lib/pgadmin

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/services/discount/Discount.API/Dockerfile
    ports:
     - "8082:8080"
    container_name: discountapi
    depends_on:
      elasticsearch:
        condition: service_healthy
      discountdb:
        condition: service_healthy

    environment:
     - ASPNETCORE_URLS=http://+:8080
     - PostgreSettings__Connection=Host=discountdb;Port=5432;Database=discountdb;Username=admin;Password=admin
     - LoggingOptions__ApplicationName=Discount.API
     - LoggingOptions__LogLevel=Information
     - LoggingOptions__ElasticUrl=http://elasticsearch:9200
    volumes:
      - discountdbdata:/data/db

      
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "9005:1433"
    restart: always
    volumes:
      - orderdbdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd' -Q 'SELECT 1'"]
      interval: 15s
      timeout: 10s
      retries: 10
    

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/services/ordering/Ordering.API/Dockerfile
    container_name: orderingapi
    ports:
      - "8083:8080"
    depends_on:
      - orderdb
      - rabbitmq
      - elasticsearch
    environment:
      - "ASPNETCORE_URLS: http://+:8080"
      - "ConnectionStrings__DefaultConnection=Server=orderdb,1433;Database=orderdb;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;"
      - "RabbitMQSetting__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - LoggingOptions__ApplicationName=Ordering.API
      - LoggingOptions__LogLevel=Information
      - LoggingOptions__ElasticUrl=http://elasticsearch:9200

    restart: always


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/Gateway/Ocelot.APIGateway/Dockerfile
    environment:
      - "ASPNETCORE_URLS: http://+:8080"
    
    ports:
      - "8085:8080"

volumes:
  catalogdbdata:
  portainer_data:
  discountdbdata:
  pgadmindata:
  orderdbdata:
  esdata:
