services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/services/catalog/Catalog.API/Dockerfile

    ports:
     - "8080:8080"
    container_name: catalogapi
    depends_on:
     - catalogdb
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - MongoSettings__Connection=mongodb://catalogdb:27017
     - MongoSettings__DatabaseName=CatalogDb

  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - catalogdbdata:/data/db
 
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/services/basket/Basket.API/Dockerfile

    ports:
     - "8081:8080"
    container_name: basketapi
    depends_on:
     - basketdb
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - CacheSettings__Connection=basketdb:6379
     - GrpcSettings__DiscountUrl=http://discount.api:8082

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data

  discountdb:
    image: postgres:18
    container_name: discountdb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: discountdb
    restart: always 
    ports:
      - "5432:5432"
    volumes:
      - discountdbdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d discountdb"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      discountdb:
        condition: service_healthy
    restart: always
    volumes:
      - pgadmindata:/var/lib/pgadmin

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/services/discount/Discount.API/Dockerfile
    ports:
     - "8082:8080"
    container_name: discountapi
    depends_on:
      discountdb:
        condition: service_healthy
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - PostgreSettings__Connection=Host=discountdb;Port=5432;Database=discountdb;Username=admin;Password=admin

    volumes:
      - discountdbdata:/data/db

volumes:
  catalogdbdata:
  portainer_data:
  discountdbdata:
  pgadmindata:
  

